version: 2
updates:
  # Check for updates in the `package.json` and `package-lock.json` files. trying retrigger.
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: '19:36'
      timezone: America/Los_Angeles
    open-pull-requests-limit: 10
    target-branch: "master"
    labels:
      - "dependencies"
      - "dependabot"
    ignore:
    - dependency-name: express
