name: Auto Merge Dependabot PRs

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

permissions:
  contents: write
  pull-requests: write

jobs:
  status-check:
    if: contains(github.event.pull_request.labels.*.name, 'dependencies')
    runs-on: ubuntu-latest

    steps:
      - name: Wait for status check
        id: outcome
        uses: omkarkhatavkar/wait-for-status-checks@main
        with:
          ref: ${{ github.head_ref }}
          context: 'continuous-integration/travis-ci/push'
          wait-interval: 60
          count: 10
      - name: Check status
        run: |
          if [ ${{ steps.outcome.outputs.result }} == 'success' ]; then
            echo "Status check passed!"
          else
            echo "Status check failed!"
            exit 1
          fi


  auto-merge:
    if: contains(github.event.pull_request.labels.*.name, 'dependencies')
    runs-on: ubuntu-latest
    needs: status-check

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Auto-approve dependabot PR
        if: contains(github.event.pull_request.labels.*.name, 'dependencies')
        uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Auto-merge dependabot PR
        if: contains(github.event.pull_request.labels.*.name, 'dependencies')
        uses: pascalgn/automerge-action@v0.15.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
