name: Merge Dependabot PRs

on:
  schedule:
    # Runs the workflow daily at midnight (adjust as needed)
    - cron: "0 0 * * *"
  workflow_dispatch: # Allows manual triggering of the action

permissions:
  contents: write

jobs:
  fetch-and-merge-dependabot-prs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Fetch Open PRs from Dependabot
      id: fetch-dependabot-prs
      run: |
        # Fetch open PRs created by Dependabot
        response=$(curl -s -H "Accept: application/vnd.github.v3+json" \
        -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
        https://api.github.com/repos/${{ github.repository }}/pulls?state=open)

        # Filter only Dependabot PRs
        dependabot_prs=$(echo "$response" | jq -r '.[] | select(.user.login == "stadori") | .number')

        # Output the PR numbers
        echo "::set-output name=dependabot_prs::$dependabot_prs"

    - name: Check Mergeability of Dependabot PRs
      id: check-mergeable
      run: |
        mergeable_prs=""
        for pr in ${{ steps.fetch-dependabot-prs.outputs.dependabot_prs }}; do
          echo "Checking PR #$pr for mergeability..."

          # Fetch mergeable status of each PR
          pr_data=$(curl -s -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/pulls/$pr)

          mergeable=$(echo "$pr_data" | jq -r '.mergeable')
          mergeable_state=$(echo "$pr_data" | jq -r '.mergeable_state')

          if [[ "$mergeable" == "true" && "$mergeable_state" == "clean" ]]; then
            echo "PR #$pr is mergeable."
            mergeable_prs="$mergeable_prs $pr"
          else
            echo "PR #$pr is not mergeable. State: $mergeable_state"
          fi
        done

        # Output the mergeable PRs
        echo "::set-output name=mergeable_prs::$mergeable_prs"

    - name: Merge Mergeable Dependabot PRs
      if: ${{ steps.check-mergeable.outputs.mergeable_prs != '' }}
      run: |
        for pr in ${{ steps.check-mergeable.outputs.mergeable_prs }}; do
          echo "Merging PR #$pr"
          curl -s -X PUT \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -d '{"merge_method":"squash"}' \
            https://api.github.com/repos/${{ github.repository }}/pulls/$pr/merge
        done
